"""

Revision ID: 003c1077a8c1
Revises: f44e44673d94
Create Date: 2022-11-14 22:19:59.242197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003c1077a8c1'
down_revision = 'f44e44673d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
