"""

Revision ID: 1411d2ecb11e
Revises: e734f6a936a3
Create Date: 2022-11-17 19:24:34.712334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1411d2ecb11e'
down_revision = 'e734f6a936a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('mod_group', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'mod_group')
    # ### end Alembic commands ###
