"""

Revision ID: 15f62ccf1e91
Revises: a26c7c887e56
Create Date: 2022-11-14 22:12:31.769999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f62ccf1e91'
down_revision = 'a26c7c887e56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
