"""

Revision ID: 1d2d868c23f3
Revises: c5bd469f2756
Create Date: 2022-11-10 20:23:49.305128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2d868c23f3'
down_revision = 'c5bd469f2756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifications', sa.Column('mod_id', sa.VARCHAR(length=300), nullable=False))
    op.add_column('modifications', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('modifications', sa.Column('product_id', sa.VARCHAR(length=500), nullable=False))
    op.add_column('products', sa.Column('product_id', sa.VARCHAR(length=300), nullable=False))
    op.add_column('products', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=1200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'product_id')
    op.drop_column('modifications', 'product_id')
    op.drop_column('modifications', 'weight')
    op.drop_column('modifications', 'mod_id')
    # ### end Alembic commands ###
