"""

Revision ID: 30c36ae97ebd
Revises: cc43031fa073
Create Date: 2022-11-16 18:26:10.185248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c36ae97ebd'
down_revision = 'cc43031fa073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifications', sa.Column('product', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modifications', 'products', ['product'], ['id'])
    op.drop_column('modifications', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifications', sa.Column('product_id', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modifications', type_='foreignkey')
    op.drop_column('modifications', 'product')
    # ### end Alembic commands ###
