"""

Revision ID: 51addc1b4ad8
Revises: 1411d2ecb11e
Create Date: 2022-11-21 22:37:46.062436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51addc1b4ad8'
down_revision = '1411d2ecb11e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baskets', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('baskets', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baskets', 'price')
    op.drop_column('baskets', 'count')
    # ### end Alembic commands ###
