"""

Revision ID: 61ca5f4048a5
Revises: c5213afd7999
Create Date: 2022-11-29 16:57:41.749656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca5f4048a5'
down_revision = 'c5213afd7999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
