"""

Revision ID: a26c7c887e56
Revises: 6783b18803f9
Create Date: 2022-11-14 22:11:50.640347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26c7c887e56'
down_revision = '6783b18803f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
