"""

Revision ID: a821b56d2f10
Revises: 61ca5f4048a5
Create Date: 2022-12-01 19:38:23.096985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a821b56d2f10'
down_revision = '61ca5f4048a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
