"""

Revision ID: b14e7fb5dd17
Revises: 34154ac5166d
Create Date: 2022-11-26 14:29:28.865824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14e7fb5dd17'
down_revision = '34154ac5166d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
