"""

Revision ID: b505f85f8c57
Revises: 1d2d868c23f3
Create Date: 2022-11-14 21:02:20.305991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505f85f8c57'
down_revision = '1d2d868c23f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modifications', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modifications', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
