"""

Revision ID: c5213afd7999
Revises: 6cb196e35aa8
Create Date: 2022-11-29 16:51:16.272247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5213afd7999'
down_revision = '6cb196e35aa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_mod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_mod_association',
    sa.Column('baskets_id', sa.Integer(), nullable=True),
    sa.Column('baskets_mod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baskets_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['baskets_mod_id'], ['basket_mod.id'], )
    )
    op.create_table('association_prod_basket',
    sa.Column('baskets_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baskets_id'], ['basket_mod.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.drop_constraint('association_mod_basket_baskets_id_fkey', 'association_mod_basket', type_='foreignkey')
    op.create_foreign_key(None, 'association_mod_basket', 'basket_mod', ['baskets_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_mod_basket', type_='foreignkey')
    op.create_foreign_key('association_mod_basket_baskets_id_fkey', 'association_mod_basket', 'baskets', ['baskets_id'], ['id'])
    op.drop_table('association_prod_basket')
    op.drop_table('basket_mod_association')
    op.drop_table('basket_mod')
    # ### end Alembic commands ###
