"""

Revision ID: cc43031fa073
Revises: a730a1f44c43
Create Date: 2022-11-16 17:48:35.761998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc43031fa073'
down_revision = 'a730a1f44c43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifications', sa.Column('type', sa.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modifications', 'type')
    # ### end Alembic commands ###
