"""

Revision ID: d5cd3a5ad617
Revises: b505f85f8c57
Create Date: 2022-11-14 21:59:18.667643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cd3a5ad617'
down_revision = 'b505f85f8c57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
